language: node_js
node_js:
- 10
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - functions/node_modules
before_install:
  - npm i -g npm
script:
- npm run build
# TODO: Re-enable when Firebase deployment on Travis CI gets fixed
# deploy:
#   skip_cleanup: true
#   provider: firebase
#   edge: true
#   token:
#     secure: Wdvo6txqlR2DRewNcoDN2y+m9TEB2sJygTXOlfAYPf61YaIvGQvn30aDrARrxHR6AcqD3LfAtDJe9hWC3LDkOop8s/+/epE9EXZfG4vVBNkkaguqD0ST5t5ngsJaDzN9NRpa+sHNBBsD1IkytQnJUZDvMdFR/nSSAT9wR9bfFSq5aS25TJAOs0mEPBd4CpRK8d4Qoh3e+YzIcUB59fF7R6qFyEIA6joKnMFciYJE1xvbNzAZMnma96ITZThaHpbWXZttdO4Gj8Viaw46YCNbD02SfSN3Vxobj8b5plwOzWMhWeWyXFPbEzHhHA1LUzliHLoGveJw+fznjYFJ1/2a7OeV8T+n8Y2X0F4/OBamXIlKtqNvVppjkPps0GLpgxP9pv+FP0M+srO6/Zw8v034jdvGCyaXSDH1p6Qy4GgURqQ1CZtIzml97eBcNlEaXuzNtN4Ebj0YwVKbmMPWAsUofwwSUjQhUmSPy69gpXxP0yx6cCHUBu1qO9o1GmX07QwAFT0mWHogJ4F13WuEyggHXgk1SKlfiG9ZM4NRai3HqwcFaP9jJ/BWD8VZpsPzFbjeg3xX82kV51ymAPsZ8yVm8d0UKE+5f+ghG1pF3YNuy9ZR1EoH/H55RXMbeylR823giTIW86LgoafNSeIg5ppzGvwSroKV7lvCku4OetGh7HU=
#   project: giorgio-garasto
