plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
yarnPath: .yarn/releases/yarn-3.2.1.cjs
# Use classic node_modules folder
nodeLinker: node-modules
# Make sure the node_modules are not hoisted to the monorepo root
nmHoistingLimits: 'dependencies'
