name: Build, deploy and audit
'on':
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 0'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy
        uses: Dabolus/deploy-firebase@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      - name: Purge cache, audit, and report
        run: |
          # Install libgbm
          sudo apt-get -y install libgbm1
          # Install required libraries
          sudo yarn add -D -W node-fetch@3 lighthouse@9 puppeteer@11 node-telegram-bot-api@0.54
          # Run the postdeploy script
          node scripts/postdeploy.js
        env:
          REPORTER_BASE_URL: ${{ secrets.REPORTER_BASE_URL }}
          REPORTER_BOT_TOKEN: ${{ secrets.REPORTER_BOT_TOKEN }}
          REPORTER_CHAT_ID: ${{ secrets.REPORTER_CHAT_ID }}
          REPORTER_PROJECT_NAME: ${{ secrets.REPORTER_PROJECT_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
