name: Build, deploy and audit
'on':
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
  schedule:
    - cron: '0 12 * * 0'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.8.1
      - name: Install deps
        run: bun install --frozen-lockfile && bun run playwright install --with-deps
      - name: Run E2E tests
        run: bun run test:e2e
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Upload E2E artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build
        run: bun run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: Dabolus/deploy-firebase@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
