name: Build, deploy and audit
'on':
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  schedule:
    - cron: '0 12 * * 0'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: yarn install --immutable
      - name: Run E2E tests
        run: yarn test:e2e
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Upload videos and screenshots if E2E tests failed
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-report
          path: |
            cypress/screenshots
            cypress/videos
      - name: Build
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: Dabolus/deploy-firebase@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      - name: Purge cache, audit, and report
        if: github.ref == 'refs/heads/master'
        run: |
          # Install libgbm
          sudo apt-get -y install libgbm1 fonts-roboto
          # Install required libraries
          sudo yarn add -D lighthouse@9 puppeteer@13 node-telegram-bot-api@0.57 sharp@0.30
          # Run the postdeploy script
          node scripts/postdeploy.js
        env:
          REPORTER_BASE_URL: ${{ secrets.REPORTER_BASE_URL }}
          REPORTER_BOT_TOKEN: ${{ secrets.REPORTER_BOT_TOKEN }}
          REPORTER_CHAT_ID: ${{ secrets.REPORTER_CHAT_ID }}
          REPORTER_PROJECT_NAME: ${{ secrets.REPORTER_PROJECT_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
